'use client';

import { useState, useCallback } from 'react';
import TiptapEditor from './TiptapEditor';
import ImageUploadCrop from '../ImageUploadCrop';
import PexelsImagePicker from '../PexelsImagePicker';
import NotificationOverlay from '@/components/NotificationOverlay';
import BlogInspirationModal from './BlogInspirationModal';
import type { BlogPost, BlogPostAttachment, BlogPostStatus, Asset } from '@/types';

interface BlogPostEditorProps {
  expertId: string; // Required for asset isolation
  initialPost?: Partial<BlogPost>;
  defaultCoverImage?: string; // Hero image from landing page as default cover
  onSave: (post: {
    title: string;
    content: string;
    coverImage?: string;
    status: BlogPostStatus;
    tags: string[];
    attachments: BlogPostAttachment[];
  }) => Promise<void>;
  onCancel: () => void;
  isSaving?: boolean;
}

export default function BlogPostEditor({
  expertId,
  initialPost,
  defaultCoverImage,
  onSave,
  onCancel,
  isSaving = false,
}: BlogPostEditorProps) {
  // Use initialPost coverImage, then defaultCoverImage (hero), then empty
  const [title, setTitle] = useState(initialPost?.title || '');
  const [content, setContent] = useState(initialPost?.content || '');
  const [coverImage, setCoverImage] = useState(initialPost?.coverImage || defaultCoverImage || '');
  const [status] = useState<BlogPostStatus>(initialPost?.status || 'draft');
  const [attachments] = useState<BlogPostAttachment[]>(initialPost?.attachments || []);
  const [showCoverUpload, setShowCoverUpload] = useState(false);
  const [showImageUpload, setShowImageUpload] = useState(false);
  const [imageUploadResolve, setImageUploadResolve] = useState<
    ((url: string | null) => void) | null
  >(null);
  const [notification, setNotification] = useState<{
    message: string;
    type: 'warning' | 'error' | 'success';
  } | null>(null);
  const [isFormatting, setIsFormatting] = useState(false);
  const [showInspirationModal, setShowInspirationModal] = useState(false);

  const handleSubmit = async (saveStatus: BlogPostStatus) => {
    if (!title.trim()) {
      setNotification({ message: 'Please enter a title', type: 'warning' });
      return;
    }
    if (!content.trim()) {
      setNotification({ message: 'Please add some content', type: 'warning' });
      return;
    }

    // Note: excerpt and tags are auto-generated by AI on the server
    await onSave({
      title: title.trim(),
      content,
      coverImage: coverImage || undefined,
      status: saveStatus,
      tags: [], // Will be auto-generated by AI
      attachments,
    });
  };

  const handleInlineImageUpload = useCallback((): Promise<string | null> => {
    return new Promise(resolve => {
      setImageUploadResolve(() => resolve);
      setShowImageUpload(true);
    });
  }, []);

  const handleInlineImageComplete = (asset: Asset) => {
    if (imageUploadResolve) {
      imageUploadResolve(asset.croppedUrl || asset.originalUrl);
      setImageUploadResolve(null);
    }
    setShowImageUpload(false);
  };

  const handleInlineImageCancel = () => {
    if (imageUploadResolve) {
      imageUploadResolve(null);
      setImageUploadResolve(null);
    }
    setShowImageUpload(false);
  };

  const handleInsertBlogPost = (newTitle: string, newContent: string) => {
    setTitle(newTitle);
    setContent(newContent);
    setNotification({ message: 'Blog post inserted! Feel free to edit.', type: 'success' });
  };

  const handleAutoFormat = async () => {
    if (!content.trim()) {
      setNotification({ message: 'Please add some content first', type: 'warning' });
      return;
    }

    setIsFormatting(true);
    try {
      console.log('[DBG][BlogPostEditor] Auto-formatting content...');
      const response = await fetch('/api/ai/format-blog-content', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content }),
      });

      const result = await response.json();

      if (result.success && result.data?.content) {
        setContent(result.data.content);
        setNotification({ message: 'Content formatted successfully', type: 'success' });
        console.log('[DBG][BlogPostEditor] Content formatted');
      } else {
        throw new Error(result.error || 'Failed to format content');
      }
    } catch (err) {
      console.error('[DBG][BlogPostEditor] Format error:', err);
      setNotification({
        message: err instanceof Error ? err.message : 'Failed to format content',
        type: 'error',
      });
    } finally {
      setIsFormatting(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto">
      {/* Title */}
      <div className="mb-6">
        <input
          type="text"
          value={title}
          onChange={e => setTitle(e.target.value)}
          placeholder="Post title"
          className="w-full text-3xl font-bold border-0 border-b-2 border-gray-200 focus:border-blue-500 focus:ring-0 px-0 py-2 placeholder-gray-400"
        />
      </div>

      {/* Cover Image */}
      <div className="mb-6">
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Cover Image (optional)
        </label>
        {coverImage ? (
          <div className="relative">
            <img src={coverImage} alt="Cover" className="w-full h-48 object-cover rounded-lg" />
            <button
              type="button"
              onClick={() => setCoverImage('')}
              className="absolute top-2 right-2 bg-red-500 text-white px-3 py-1 rounded text-sm hover:bg-red-600"
            >
              Remove
            </button>
            <button
              type="button"
              onClick={() => setShowCoverUpload(true)}
              className="absolute top-2 right-20 bg-gray-700 text-white px-3 py-1 rounded text-sm hover:bg-gray-800"
            >
              Change
            </button>
          </div>
        ) : (
          <button
            type="button"
            onClick={() => setShowCoverUpload(true)}
            className="w-full h-32 border-2 border-dashed border-gray-300 rounded-lg flex items-center justify-center text-gray-500 hover:border-gray-400 hover:text-gray-600 transition-colors"
          >
            + Add cover image
          </button>
        )}
      </div>

      {/* Content Editor */}
      <div className="mb-6">
        <div className="flex items-center justify-between mb-2">
          <label className="block text-sm font-medium text-gray-700">Content</label>
          <button
            type="button"
            onClick={() => setShowInspirationModal(true)}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-lg transition-colors"
            style={{ color: 'var(--color-primary)', backgroundColor: 'var(--color-primary-light)' }}
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
              />
            </svg>
            Need inspiration?
          </button>
        </div>
        <TiptapEditor
          content={content}
          onChange={setContent}
          onImageUpload={handleInlineImageUpload}
          placeholder="Write your blog post content here..."
        />
        {/* Auto Format Button */}
        <div className="mt-3 flex justify-end">
          <button
            type="button"
            onClick={handleAutoFormat}
            disabled={isFormatting || !content.trim()}
            className="inline-flex items-center gap-2 px-4 py-2 text-sm text-gray-600 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isFormatting ? (
              <>
                <svg
                  className="animate-spin h-4 w-4"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  />
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  />
                </svg>
                Formatting...
              </>
            ) : (
              <>
                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                  />
                </svg>
                Auto Format
              </>
            )}
          </button>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex justify-between items-center pt-6 border-t border-gray-200">
        <button
          type="button"
          onClick={onCancel}
          className="px-4 py-2 text-gray-600 hover:text-gray-800 transition-colors"
          disabled={isSaving}
        >
          Cancel
        </button>
        <div className="flex gap-3">
          <button
            type="button"
            onClick={() => handleSubmit('draft')}
            className="px-6 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50"
            disabled={isSaving}
          >
            {isSaving ? 'Saving...' : 'Save Draft'}
          </button>
          <button
            type="button"
            onClick={() => handleSubmit('published')}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50"
            disabled={isSaving}
          >
            {isSaving ? 'Publishing...' : status === 'published' ? 'Update' : 'Publish'}
          </button>
        </div>
      </div>

      {/* Cover Image Upload Modal */}
      {showCoverUpload && (
        <div className="fixed inset-0 bg-white/20 backdrop-blur-sm flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
            <h3 className="text-lg font-semibold mb-4">Choose Cover Image</h3>
            <PexelsImagePicker
              width={1200}
              height={630}
              category="blog_cover"
              tenantId={expertId}
              defaultSearchQuery="blog writing"
              onImageSelect={imageUrl => {
                setCoverImage(imageUrl);
                setShowCoverUpload(false);
              }}
              onError={error => {
                console.error('Cover image error:', error);
                setNotification({ message: 'Failed to set cover image', type: 'error' });
              }}
              currentImageUrl={coverImage}
            />
            <button
              type="button"
              onClick={() => setShowCoverUpload(false)}
              className="mt-4 w-full px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Inline Image Upload Modal */}
      {showImageUpload && (
        <div className="fixed inset-0 bg-white/20 backdrop-blur-sm flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 max-w-2xl w-full mx-4">
            <h3 className="text-lg font-semibold mb-4">Insert Image</h3>
            <ImageUploadCrop
              width={800}
              height={600}
              category="blog_inline"
              tenantId={expertId}
              onUploadComplete={handleInlineImageComplete}
              onError={error => {
                console.error('Image upload error:', error);
                setNotification({ message: 'Failed to upload image', type: 'error' });
                handleInlineImageCancel();
              }}
              label="Blog Image"
            />
            <button
              type="button"
              onClick={handleInlineImageCancel}
              className="mt-4 w-full px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Blog Inspiration Modal */}
      <BlogInspirationModal
        isOpen={showInspirationModal}
        onClose={() => setShowInspirationModal(false)}
        onInsertBlogPost={handleInsertBlogPost}
      />

      {/* Notification Overlay */}
      <NotificationOverlay
        isOpen={notification !== null}
        onClose={() => setNotification(null)}
        message={notification?.message || ''}
        type={notification?.type || 'warning'}
        duration={4000}
      />
    </div>
  );
}
